services:
  pychrono:
    environment:
      # Forward X11 display to container
      - DISPLAY=${DISPLAY}
      # Forward host user id and group id to manage folder ownership
      - UID=${HOST_UID}
      - GID=${HOST_GID}
    user: "${HOST_UID}:${HOST_GID}"
    volumes: 
      # Mount X11 socket for GUI applications
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      # Mount PyChronoSharedFolder folder 
      - type: bind
        source: ${HOST_SHARED_DIR}
        target: /home/user/PyChronoSharedFolder
